[build]
  publish = "public/experts"
  command = "hugo --gc --minify --destination public/experts"

  [build.environment]
    HUGO_VERSION = "0.118.2"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo --destination public/experts"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b ${DEPLOY_PRIME_URL}/experts/"

[context.branch-deploy]
  command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}/experts/"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"